# booking-service/app/db/models.py
#
# SQLAlchemy ORM models for the Booking Service.
#
# Defines two tables:
#   - flights   → read-only inventory seeded by database/init/01_schema.sql
#   - bookings  → written by the Booking Service as events are processed
#
# Design principles:
#   - Every column has an explicit type, nullable flag, and comment so the
#     generated schema is self-documenting in psql and DB admin tools.
#   - No foreign key constraints between bookings and flights at the DB level.
#     The Booking Service enforces referential integrity in service.py by
#     querying the flights table before inserting. Removing the FK constraint
#     allows the two tables to be migrated and scaled independently without
#     cascading lock issues on a high-write bookings table.
#   - Audit timestamps (requested_at, confirmed_at, failed_at) are stored in
#     UTC and set by the application — not by PostgreSQL DEFAULT NOW() — so
#     they reflect the time the event was processed, not the time the DB row
#     was written (the two can differ under retry conditions).
#   - All UUID primary keys are stored as VARCHAR(36) rather than PostgreSQL's
#     native UUID type so the models stay portable across databases in tests
#     (SQLite does not have a UUID type).

from __future__ import annotations

from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    Column,
    DateTime,
    Integer,
    Numeric,
    String,
    Text,
    Index,
    UniqueConstraint,
    CheckConstraint,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


# ──────────────────────────────────────────────────────────────────────────────
# DECLARATIVE BASE
# All ORM models inherit from Base. Alembic reads Base.metadata to generate
# migration files via `alembic revision --autogenerate`.
#
# Using DeclarativeBase (SQLAlchemy 2.x) rather than the legacy
# declarative_base() factory. The 2.x API supports typed mapped_column()
# declarations which give IDE autocompletion and runtime type safety.
# ──────────────────────────────────────────────────────────────────────────────

class Base(DeclarativeBase):
    """
    Base class for all ORM models in the Booking Service.

    Importing this class in alembic/env.py and calling
    `target_metadata = Base.metadata` is all Alembic needs to detect
    schema changes and generate migration scripts automatically.
    """
    pass


# ──────────────────────────────────────────────────────────────────────────────
# FLIGHT MODEL
# Represents available flights. Populated by database/init/01_schema.sql
# seed data and treated as read-only by the Booking Service — no INSERT
# or UPDATE is performed against this table in service.py.
#
# In a production system this table would be owned and written by a separate
# Flight Inventory Service. The Booking Service queries it to verify that a
# flight exists before creating a booking.
# ──────────────────────────────────────────────────────────────────────────────

class Flight(Base):
    """
    Represents a single scheduled flight in the inventory.

    Read-only from the Booking Service's perspective. Written by the
    Flight Inventory Service (or seeded via SQL in this project).
    """

    __tablename__ = "flights"

    # ── PRIMARY KEY ───────────────────────────────────────────────────────────

    flight_id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        comment="UUID generated by the Flight Inventory Service",
    )

    # ── FLIGHT IDENTIFICATION ─────────────────────────────────────────────────

    flight_number: Mapped[str] = mapped_column(
        String(10),
        nullable=False,
        comment="IATA flight number e.g. AA123, BA4567",
    )

    # IATA 3-letter airport codes stored in uppercase
    origin: Mapped[str] = mapped_column(
        String(3),
        nullable=False,
        comment="IATA departure airport code e.g. JFK",
    )

    destination: Mapped[str] = mapped_column(
        String(3),
        nullable=False,
        comment="IATA arrival airport code e.g. LAX",
    )

    # ── SCHEDULE ──────────────────────────────────────────────────────────────

    departure_time: Mapped[datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        comment="Scheduled departure time in UTC",
    )

    arrival_time: Mapped[datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        comment="Scheduled arrival time in UTC",
    )

    # ── CAPACITY ──────────────────────────────────────────────────────────────

    total_seats: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Total seat count across all cabin classes",
    )

    available_seats: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment=(
            "Remaining available seats — decremented by Seat Service "
            "when a Redis lock is acquired. Read-only for Booking Service."
        ),
    )

    # ── STATUS ────────────────────────────────────────────────────────────────

    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="scheduled",
        comment="Flight status: scheduled | boarding | departed | arrived | cancelled",
    )

    # ── AUDIT ─────────────────────────────────────────────────────────────────

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        default=datetime.utcnow,
        comment="UTC timestamp when the flight record was created",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        comment="UTC timestamp of the last update to this record",
    )

    # ── TABLE ARGS ────────────────────────────────────────────────────────────

    __table_args__ = (
        # Enforce that arrival is always after departure at the DB level.
        # service.py also validates this in the Pydantic model but defence
        # in depth catches any path that bypasses application-level validation.
        CheckConstraint(
            "arrival_time > departure_time",
            name="ck_flights_arrival_after_departure",
        ),

        # Enforce non-negative seat counts — prevents inventory going negative
        # due to a race condition between concurrent seat lock acquisitions.
        CheckConstraint(
            "available_seats >= 0",
            name="ck_flights_available_seats_non_negative",
        ),
        CheckConstraint(
            "total_seats > 0",
            name="ck_flights_total_seats_positive",
        ),

        # Index on (origin, destination, departure_time) for the common query
        # pattern: "find all flights from JFK to LAX departing tomorrow".
        Index(
            "ix_flights_route_departure",
            "origin",
            "destination",
            "departure_time",
        ),

        # Index on flight_number for lookups by flight number from the API.
        Index("ix_flights_flight_number", "flight_number"),

        {"comment": "Available flight inventory — read-only for Booking Service"},
    )

    def __repr__(self) -> str:
        return (
            f"<Flight "
            f"flight_id={self.flight_id!r} "
            f"flight_number={self.flight_number!r} "
            f"origin={self.origin!r} "
            f"destination={self.destination!r} "
            f"departure={self.departure_time!r}"
            f">"
        )


# ──────────────────────────────────────────────────────────────────────────────
# BOOKING MODEL
# The primary write model of the Booking Service. One row is created per
# BookingRequestedEvent and updated as subsequent events (seat.reserved,
# payment.processed, payment.failed) are processed.
#
# Status lifecycle:
#
#   REQUESTED  →  SEAT_HELD  →  PAYMENT_PENDING  →  CONFIRMED
#                                                  ↘
#                     FAILED  ←─── seat.unavailable / payment.failed
#
# All status transitions are enforced in service.py, not at the DB level,
# so the service can produce meaningful error messages rather than a raw
# PostgreSQL check constraint violation.
# ──────────────────────────────────────────────────────────────────────────────

class Booking(Base):
    """
    Represents a single flight booking and its full lifecycle.

    Created when BookingRequestedEvent is consumed from `booking.requested`.
    Updated as seat reservation and payment events arrive on subsequent topics.
    """

    __tablename__ = "bookings"

    # ── PRIMARY KEY ───────────────────────────────────────────────────────────

    booking_id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        comment=(
            "UUID generated by the API Gateway and propagated through all "
            "downstream events. Used as the Kafka message key so all events "
            "for the same booking land on the same partition."
        ),
    )

    # ── TRACING ───────────────────────────────────────────────────────────────

    correlation_id: Mapped[str] = mapped_column(
        String(36),
        nullable=False,
        comment=(
            "Trace ID shared across all services for this booking request. "
            "Join on this column to reconstruct the full event journey in logs."
        ),
    )

    # ── PASSENGER FIELDS ──────────────────────────────────────────────────────
    # Denormalised from the BookingRequestedEvent payload. Storing them here
    # means booking queries do not need to JOIN a separate passengers table
    # and remain fast even under high read load.

    passenger_id: Mapped[str] = mapped_column(
        String(36),
        nullable=False,
        comment="UUID of the passenger from the users/passengers table",
    )

    passenger_first_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="Passenger legal first name as submitted in the booking request",
    )

    passenger_last_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="Passenger legal last name as submitted in the booking request",
    )

    passenger_email: Mapped[str] = mapped_column(
        String(254),
        nullable=False,
        comment="Contact email — used by Notification Service for confirmation",
    )

    passenger_phone: Mapped[str | None] = mapped_column(
        String(30),
        nullable=True,
        comment="E.164 phone number — required for SMS notifications",
    )

    passport_number: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        comment="Passport number — required for international flights",
    )

    # ── FLIGHT FIELDS ─────────────────────────────────────────────────────────
    # Also denormalised from the event payload. Storing flight details inline
    # means a booking record is a complete snapshot of what was booked at the
    # time — immune to changes in the flights table after the fact.

    flight_id: Mapped[str] = mapped_column(
        String(36),
        nullable=False,
        comment="UUID of the booked flight — not a FK, see module docstring",
    )

    flight_number: Mapped[str] = mapped_column(
        String(10),
        nullable=False,
        comment="IATA flight number at time of booking e.g. AA123",
    )

    origin: Mapped[str] = mapped_column(
        String(3),
        nullable=False,
        comment="IATA departure airport code at time of booking",
    )

    destination: Mapped[str] = mapped_column(
        String(3),
        nullable=False,
        comment="IATA arrival airport code at time of booking",
    )

    departure_time: Mapped[datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        comment="Scheduled departure time in UTC at time of booking",
    )

    arrival_time: Mapped[datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        comment="Scheduled arrival time in UTC at time of booking",
    )

    # ── SEAT FIELDS ───────────────────────────────────────────────────────────

    seat_number: Mapped[str] = mapped_column(
        String(4),
        nullable=False,
        comment="Seat identifier e.g. 12A — locked in Redis by Seat Service",
    )

    seat_class: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        comment="Cabin class: economy | premium_economy | business | first",
    )

    # ── PRICING FIELDS ────────────────────────────────────────────────────────

    total_price: Mapped[Decimal] = mapped_column(
        # Numeric(10, 2) stores up to 99,999,999.99 with 2 decimal places.
        # Use Numeric rather than Float — Float is a binary floating point
        # type that cannot represent values like 0.10 exactly, which causes
        # rounding errors in financial calculations.
        Numeric(10, 2),
        nullable=False,
        comment="Total fare charged in the specified currency",
    )

    currency: Mapped[str] = mapped_column(
        String(3),
        nullable=False,
        default="USD",
        comment="ISO 4217 currency code e.g. USD, EUR, GBP",
    )

    # ── PAYMENT FIELDS ────────────────────────────────────────────────────────
    # Populated when payment.processed is consumed. NULL until payment succeeds.

    payment_id: Mapped[str | None] = mapped_column(
        String(36),
        nullable=True,
        comment="UUID of the payment transaction from Payment Service",
    )

    payment_amount: Mapped[Decimal | None] = mapped_column(
        Numeric(10, 2),
        nullable=True,
        comment="Amount actually charged — may differ from total_price if refunded",
    )

    payment_currency: Mapped[str | None] = mapped_column(
        String(3),
        nullable=True,
        comment="Currency of the actual charge — may differ if FX conversion applied",
    )

    payment_method: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
        comment="Payment method used e.g. credit_card, paypal, stripe",
    )

    transaction_ref: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        comment="External transaction reference from Stripe or payment provider",
    )

    # ── NOTIFICATION PREFERENCE ───────────────────────────────────────────────

    notification_type: Mapped[str] = mapped_column(
        String(10),
        nullable=False,
        default="email",
        comment="How the passenger wants their confirmation: email | sms | both",
    )

    # ── STATUS ────────────────────────────────────────────────────────────────

    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="requested",
        comment=(
            "Current lifecycle status of the booking. "
            "Transitions: requested → seat_held → payment_pending "
            "→ confirmed | failed | cancelled"
        ),
    )

    # ── FAILURE TRACKING ──────────────────────────────────────────────────────
    # Populated only when status transitions to FAILED.

    failure_reason: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment=(
            "Human-readable failure reason populated when status=failed. "
            "Examples: 'Seat already reserved', 'Card declined', "
            "'Flight not found in database'"
        ),
    )

    # ── AUDIT TIMESTAMPS ──────────────────────────────────────────────────────
    # All set by the application in UTC. See module docstring for why we
    # use application-set timestamps rather than PostgreSQL DEFAULT NOW().

    requested_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=False),
        nullable=True,
        comment="UTC time the BookingRequestedEvent was processed",
    )

    confirmed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=False),
        nullable=True,
        comment="UTC time the PaymentProcessedEvent was processed (happy path)",
    )

    failed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=False),
        nullable=True,
        comment="UTC time the booking was marked FAILED",
    )

    cancelled_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=False),
        nullable=True,
        comment="UTC time the booking was cancelled by the passenger (future feature)",
    )

    # ── TABLE ARGS ────────────────────────────────────────────────────────────

    __table_args__ = (
        # Prevent two bookings for the same passenger on the same flight
        # in the same seat. A passenger cannot book seat 12A on AA123 twice.
        # Note: this constraint allows different passengers to book the same
        # seat on different flights — the (flight_id, seat_number) combination
        # is constrained to one CONFIRMED booking by Seat Service's Redis lock,
        # not by this DB constraint.
        UniqueConstraint(
            "passenger_id",
            "flight_id",
            "seat_number",
            name="uq_bookings_passenger_flight_seat",
        ),

        # Status must be one of the known lifecycle values.
        # Prevents service bugs from writing arbitrary strings to this column.
        CheckConstraint(
            "status IN ('requested','seat_held','payment_pending',"
            "'confirmed','failed','cancelled')",
            name="ck_bookings_status_valid",
        ),

        # Prices must be positive — a zero or negative booking price indicates
        # a data error, not a valid free ticket (those would have a special
        # promo_code column in a production system).
        CheckConstraint(
            "total_price > 0",
            name="ck_bookings_total_price_positive",
        ),

        # ── INDEXES ───────────────────────────────────────────────────────────

        # Primary lookup pattern: "get all bookings for passenger X"
        # Used by GET /bookings?passenger_id=... on a future read API.
        Index("ix_bookings_passenger_id", "passenger_id"),

        # Used by service.py idempotency checks in every handler.
        # booking_id is already the primary key (and therefore indexed),
        # but an explicit index declaration makes the intent clear.
        # SQLAlchemy will not create a duplicate index — PK index suffices.
        # Index("ix_bookings_booking_id", "booking_id"),  # redundant with PK

        # Used by monitoring queries: "how many bookings are in each status?"
        Index("ix_bookings_status", "status"),

        # Used for correlation tracing: "find all DB records for correlation X"
        Index("ix_bookings_correlation_id", "correlation_id"),

        # Composite index for the common admin query pattern:
        # "find all bookings on flight X that are confirmed"
        Index(
            "ix_bookings_flight_status",
            "flight_id",
            "status",
        ),

        # Composite index for time-range queries on the bookings dashboard:
        # "show me all bookings requested in the last 24 hours"
        Index(
            "ix_bookings_status_requested_at",
            "status",
            "requested_at",
        ),

        {"comment": "Booking lifecycle records written by Booking Service"},
    )

    def __repr__(self) -> str:
        return (
            f"<Booking "
            f"booking_id={self.booking_id!r} "
            f"passenger_id={self.passenger_id!r} "
            f"flight_id={self.flight_id!r} "
            f"seat={self.seat_number!r} "
            f"status={self.status!r}"
            f">"
        )

    # ── CONVENIENCE PROPERTIES ────────────────────────────────────────────────

    @property
    def passenger_full_name(self) -> str:
        """
        Return the passenger's full name as a single string.
        Used by Notification Service templates when formatting confirmation
        emails: "Dear Jane Doe, your booking is confirmed."
        """
        return f"{self.passenger_first_name} {self.passenger_last_name}"

    @property
    def is_terminal(self) -> bool:
        """
        True if the booking has reached a terminal state from which no
        further status transitions are possible.

        Used in service.py to short-circuit processing of late-arriving
        events (e.g. a seat.reserved event arriving after the booking
        was already cancelled).
        """
        return self.status in ("confirmed", "failed", "cancelled")

    @property
    def duration_minutes(self) -> int | None:
        """
        Return the flight duration in minutes, or None if either timestamp
        is not set. Used in confirmation email templates to show passengers
        their total flight time.
        """
        if self.departure_time and self.arrival_time:
            delta = self.arrival_time - self.departure_time
            return int(delta.total_seconds() / 60)
        return None